services:
  - type: web
    name: g7-store-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
